### ISSUE TITLE
Links to .git files

### ISSUE THREAD

**Issue by daybyter** [puppeh/gcc-6502-bits#1]
The git links in the readme.md did not work for me due to missing access rights. 

Had to use the links from the github websit, like 

https://github.com/puppeh/gcc-6502-bits.git

(no git@ ...).

Was able to compile the compiler then. Very cool project! Thanks!

**Comment by itszor** [comment]
On Mon, May 09, 2016 at 10:10:54AM -0700, daybyter wrote:

> The git links in the readme.md did not work for me due to missing access rights. 
> 
> Had to use the links from the github websit, like 
> 
> https://github.com/puppeh/gcc-6502-bits.git
> 
> (no git@ ...).
> 
> Was able to compile the compiler then. Very cool project! Thanks!

Thank you! I've updated the README.md file with https links instead.

Cheers,

Julian
