### ISSUE TITLE
c64 fputc  ( gcc-6502-bits/libtinyc/c64/fputc.c )

### ISSUE THREAD

**Issue by daybyter** [puppeh/gcc-6502-bits#2]
I think the easiest way to print a character here is the kernal CHROUT function at $ffd2 ?

http://sta.c64.org/cbm64krnfunc.html

just a 

lda #<character>
jsr $ffd2

should do the job?

**Comment by itszor** [comment]
This should be fixed (apart from character encoding issues) by Claus64's pull request #3, I think.
